### ISSUE TITLE
Criação de Rich Pictures e do Documento Principal

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#1]
## Descrição da Issue
Adição dos rich pictures individuais e criação do documento principal contento explicação, fotos e demais artefatos de pré-elicitação. Cada um dos integrantes adicionar a foto do rich picture nos comentários

## Tasks:
- [x] Criação dos rich pictures individuais
- [x] Escolha do rich picture principal
- [ ] (Opcional) digitalização do rich picture
- [x] Documento de pré-elicitação Rich Picture

**Comment by Joao-Moura** [comment]
![image](https://user-images.githubusercontent.com/46077033/151263356-699a194a-939a-45ab-8b06-0e07b42c5a84.png)

**Comment by CarlosFiuza** [comment]
![rich_picture](https://user-images.githubusercontent.com/71738659/151265541-8b5abbf1-0934-481b-8710-95181c6107b8.png)

**Comment by brenno-silva** [comment]
![IMG_20220126_211526_2](https://user-images.githubusercontent.com/54643530/151268508-108e6439-c91f-4174-8cb9-d1ed11ccb648.jpg)

**Comment by oEduardoAfonso** [comment]
![rich_picutre](https://user-images.githubusercontent.com/54921791/151271401-c5df0e60-9381-4316-a5cf-8023ef430832.jpg)

**Comment by RcleydsonR** [comment]
![image](https://user-images.githubusercontent.com/74625814/151279003-2769ff26-5c63-4a81-aa43-3ff44264493f.png)

**Comment by thiagohdaqw** [comment]
![rich_picture_thiago](https://user-images.githubusercontent.com/54081877/151404727-ac43fd0a-4a7c-4634-aecc-1c11b7c11d19.png)

**Comment by Denniel-sudo** [comment]
![Rich_Picture_Denniel](https://user-images.githubusercontent.com/54074370/151438550-0d5e0d1b-f856-41ac-b206-0f07ba6ebd5d.jpg)

**Comment by VitorLamego** [comment]
![Frame 1](https://user-images.githubusercontent.com/54643464/151442190-d0399928-c0d6-49e0-a1e6-8ef4254efbb9.png)

**Comment by VitorLamego** [comment]
![Frame 1](https://user-images.githubusercontent.com/54643464/151442301-18e977a6-cc69-4562-9f9d-61d4a3157ff6.svg)

**Comment by PauloAbiAcl** [comment]
![WhatsApp Image 2022-01-27 at 23 18 50](https://user-images.githubusercontent.com/78428733/151476481-42ee9453-8e3f-416a-89e5-d77c3c9a668a.jpeg)

**Comment by vital14** [comment]
![Screenshot_20220128-000603_Drive.jpg](https://user-images.githubusercontent.com/54643459/151480425-a784e5a1-5ae5-412a-a1ac-85a672f7f2ec.jpg)

**Comment by Joao-Moura** [comment]
Concluído
