### ISSUE TITLE
Dojo Flutter

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#102]
## Descrição da Issue
Documentar como foi feito o dojo para a parte de mobile do app

## Tasks:
- [x] Realizar o dojo
- [x] Disponibilizar para o resto da equipe
- [x] Documentar na wiki

## Critérios de Aceitação:
- [x] Ser aceito por um membro
