### ISSUE TITLE
[US01] - Cadastro de técnicos

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#105]
## Descrição da Issue

Criação do endpoint de criação (POST) para o técnico

## Tasks:

- [x] Novo endpoint de criação de técnico
- [x] Model de Técnico
- [x] Serializers de criação

## Critérios de Aceitação:

- [x] Endpoints testados
