### ISSUE TITLE
[US04] - Login de usuário na aplicação

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#106]
## Descrição da Issue

Adição dos endpoints necessários para o fluxo de login e dos tokens de todo o sistema

## Tasks:

- [x] Criação do endpoint de login
- [x] Criação do endpoint de refresh
- [x] Criação do endpoint de verify
- [ ] (Extra) Traduzir mensagens de erro

## Critérios de Aceitação:

- [x] Testes unitários
