### ISSUE TITLE
[US06] - Cadastro de produtor e registro geral de usuário

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#107]
## Descrição da Issue

Criação do endpoint de criação (POST) para o produtor

## Tasks:

- [x] Novo endpoint de criação de produtores
- [x] Models de Usuario Abstrato e Produtor
- [x] Serializers de criação

## Critérios de Aceitação:

- [x] Endpoints testados

**Comment by Joao-Moura** [comment]
Concluido
