### ISSUE TITLE
Tela de Cadastro

### ISSUE THREAD

**Issue by oEduardoAfonso** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#110]
## Descrição da Issue

Criar a tela de cadastro de usuário

## Tasks:
- [x] Criar os componentes
- [x] Criar as validações dos campos
- [x] Enviar requisição pro backend
- [x] Configurar navigation entre telas

## Critérios de Aceitação:
- [x] Tela criada e testada
