### ISSUE TITLE
Tela de Login

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#111]
## Descrição da Issue
Desenvolver o design da tela de login

## Tasks:
- [x] Desenvolver design
- [x] Realizar validação de campos
- [x] Integrar com o back ( se possível )

## Critérios de Aceitação:
 - [x] Seguir o design do Protótipo de Alta Fidelidade
