### ISSUE TITLE
CI/CD Pipeline backend

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#115]
## Descrição da Issue

Essa task se responsabiliza em configurar as automatizações necessárias para o melhor trabalho entre os integrantes do back-end.

## Tasks:
- [x] Configurar Makefile
- [x] Configurar CI com testes (codecov) e lint
- [x] Configurar deploy
- [x] Configurar qa contínuo (sonarcloud, codeclimate ou outro...)

## Critérios de Aceitação:
- [x] Aprovação dos integrantes do back referente principalmente as métricas estabelecidades

**Comment by RcleydsonR** [comment]
Done
