### ISSUE TITLE
Tela de seleção do tipo de conta

### ISSUE THREAD

**Issue by vital14** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#116]
## Descrição da Issue
Criação da tela para escolha de conta de produtor ou técnico

## Tasks:
- [x] Criação da tela
- [x] Linkagem com as outras telas

## Critérios de Aceitação:
- [x] Estar de acordo com o protótipo
- [x] Funcionar como o esperado
