### ISSUE TITLE
[US07] - Cadastro de propriedade

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#117]
## Descrição da Issue

Criação do endpoint de criação (POST) para a propriedade

## Tasks:
- [x] Novo endpoint de criação de propriedade
- [x] Models de propriedade
- [x] Serializers de criação

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
