### ISSUE TITLE
Solução Modelagem/Código de GOFs Criacionais

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#118]
## Descrição da Issue

Devem ser discutidos, editados e implementados novas, ou melhorando, funcionalidades e as modelagens do projeto para suprir as necessidades de GoFs Criacionais

## Tasks:

- [x] Dois exemplos da utilização na modelagem
- [x] Dois exemplos de codificações implementadas

## Critérios de Aceitação:

- [x] 4 exemplos no documento
