### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by vital14** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#122]
## Descrição da Issue
Criação da página de carregamento, splash screen

## Tasks:
- [ ] Criação da tela de acordo com o protótipo

## Critérios de Aceitação: 
- [ ] Carregar a página e cair na de login
- [ ] Estar de acordo com o protótipo
