### ISSUE TITLE
Aplicação GOFs Comportamentais

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#123]
## Descrição da Issue
Desenvolver documento de aplicação do padrão GOFs comportamentais utilizado no projeto.

## Tasks:
- [x] Abrir documento
- [x] Colocar breve explicação da utilização em código
- [x] Colocar trecho do código mostrando onde foi utilizado

## Critérios de Aceitação:
- [x] Ser revisado por 2 membros
- [x] Ter pelo menos dois padrões de projeto GOFs Comportamental

**Comment by Joao-Moura** [comment]
Feito
