### ISSUE TITLE
Aplicação dos Padrões emergentes

### ISSUE THREAD

**Issue by Denniel-sudo** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#128]
## Descrição da Issue
Criação de exemplos dos padrões emergentes utilizando do que foi desenvolvido no projeto

## Tasks:
- [x] Escolher um padrão emergente para exemplificar
- [x] Encontrar o padrão no projeto
- [x] Retirar e documentar o padrão exemplificando com imagens do projeto

## Critérios de Aceitação:
- [x] Padrão ser aplicado no projeto
- [x] Ter ao menos um exemplo
- [x] Utilizar de imagens

**Comment by Joao-Moura** [comment]
Concluído
