### ISSUE TITLE
Estilos e Padrões Arquiteturais Parte 4

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#135]
## Descrição da Issue
Desenvolver documento relacionado ao estudo de "Estilos e Padrões Arquiteturais" com foco nos assuntos detalhados na Parte 4.

## Tasks:
- [x] Padrão Arquitetural Orientado a Eventos
- [x] Padrão Arquitetural Orientado a Serviços
- [x] Pontos positivos e negativos

## Critérios de Aceitação:
- [x] Revisado e compreendido por outro membro do grupo

**Comment by Joao-Moura** [comment]
Feito
