### ISSUE TITLE
Documento de Arquitetura de Software

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#136]
## Descrição da Issue
Desenvolvimento do documento de arquitetura de software contendo as diversas visões do projeto

## Tasks:
- [x] 1. Documentação da introdução
- [x] 2. Documento da representação arquitetural
- [x] 3. Documentação das metas e restrições da arquitetura
- [x] 4. Documentação da visão Use-Case do projeto
- [x] 5. Documentação da visão lógica levando em consideração os pacotes e relacionamento
- [x] 6. Documentação das visões de processo
- [x] 7. Documentação da visão de implantação
- [x] 8. Documentação da visão de implementação
- [x] 9. Documentação da visão de banco de dados
- [x] 10. Documentação do tamanho e da performance
- [x] 11. Documentação de qualidade

## Critérios de Aceitação:
- [x] Aceitação de dois ou três membros que não devem revisar as suas respectivas contribuições para o documento, ficando a cargo dos outros revisores.
