### ISSUE TITLE
[US13] - Cadastro de Plantação e Culturas

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#146]
## Descrição da Issue

Criação do endpoint de criação (POST) para a plantação e para as culturas

## Tasks:
- [x] Novo endpoint de criação de plantação
- [x] Models de plantação
- [x] Serializers de plantação
- [x] Novo endpoint de criação de culturas
- [x] Models de culturas
- [x] Serializers de culturas

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
