### ISSUE TITLE
Documento de Reutilização de Software

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#147]
## Descrição da Issue
Desenvolvimento do documento de reutilização de software para o docker, front e back do projeto.

## Tasks:
- [x] 1. Reutilização Docker
- [x] 2. Reutilização Flutter (Frontend)
- [x] 3. Reutilização Django (Backend)

## Critérios de Aceitação:
- [x] Aceitação de dois ou três membros
