### ISSUE TITLE
[US20] Cadastro de Agrotóxico

### ISSUE THREAD

**Issue by thiagohdaqw** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#148]
## Descrição da Issue

Criação do endpoint de criação (POST) para a agrotoxico

## Tasks:

- [x]  Novo endpoint de criação de agrotoxico
- [x]  Models de agrotoxico
- [x]  Serializers de agrotoxico

## Critérios de Aceitação:

- [x] Revisado pelo time de back-end
- [x]  Passar nos testes de integração contínua.
