### ISSUE TITLE
Estilos e Padrões Arquiteturais Parte 2

### ISSUE THREAD

**Issue by Denniel-sudo** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#150]
## Descrição da Issue
Criação da parte 2 dos padrões arquiteturais

## Tasks:
- [ ] Criar documento
- [ ] Identificar estilo arquitetural
- [ ] Explicar estilo arquitetural

## Critérios de Aceitação:
- [ ] Documento criado
- [ ] Estilo arquitetural identificado
- [ ] Estilo arquitetural documentado
