### ISSUE TITLE
US26 - Visualização de propriedade

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#154]
## Descrição da Issue

Criação do endpoint de  visualização (GET) da propriedade

## Tasks:
- [x] Novo endpoint de visualização de propriedade

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.

**Comment by RcleydsonR** [comment]
Done
