### ISSUE TITLE
US24 - Visualização de plantações

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#156]
## Descrição da Issue

Criação do endpoint de  visualização (GET) de plantações

## Tasks:
- [x] Novo endpoint de visualização de propriedade
- [ ] Implementação de filtros

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
