### ISSUE TITLE
Tela de Propriedade

### ISSUE THREAD

**Issue by CarlosFiuza** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#160]
## Descrição da Issue
Realizar a implentação da tela de Propriedade seguindo protótipo figma

## Tasks:
- [x] Contruir tela
- [x] Realizar conexão com a api

## Critérios de Aceitação:
- [x] Estar de acordo com protótipo
- [x] Seguir o fluxo do app
