### ISSUE TITLE
Tela Adicionar Plantação

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#162]
## Descrição da Issue
Criar a tela de adição de plantação e realizar a implementação para o projeto.

## Tasks:
- [x] Criação da interface no Protótipo do projeto
- [x] Implementação da tela

## Critérios de Aceitação:
- [x] Estar de acordo com a identidade visual do projeto
- [x] Seguir os padrões de código definidos pelo grupo
