### ISSUE TITLE
Tela Adicionar Agrotóxico

### ISSUE THREAD

**Issue by oEduardoAfonso** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#164]
## Descrição da Issue
Criar a tela de adição de agrotóxico e realizar a implementação para o projeto.

## Tasks:
- [x] Criação da interface no Protótipo do projeto
- [x] Adição dos endpoints necessario para a tela
- [x] Implementação da tela

## Critérios de Aceitação:
- [x] Estar de acordo com a identidade visual do projeto
- [x] Seguir os padrões de código definidos pelo grupo

**Comment by Joao-Moura** [comment]
Backend concluido para essa task
