### ISSUE TITLE
US03 - Edição de Usuário

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#166]
## Descrição da Issue

Criação do endpoint de atualização (PATCH/PUT) de usuários

## Tasks:
- [x] Novo endpoint de atualização de usuários

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
