### ISSUE TITLE
US08 - Edição de Propriedade

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#167]
## Descrição da Issue

Criação do endpoint de  atualização (PATCH/PUT) de propriedade

## Tasks:
- [x] Novo endpoint de atualização de propriedade

## Critérios de Aceitação:
- [ ] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.

**Comment by RcleydsonR** [comment]
Excelente trabalho
