### ISSUE TITLE
US21 - Remoção de Agrotóxico

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#168]
## Descrição da Issue

Criação do endpoint de remoção (DELETE) de agrotóxico

## Tasks:
- [x] Novo endpoint de remoção de agrotóxico

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.

**Comment by Joao-Moura** [comment]
Feito
