### ISSUE TITLE
US12 - Remover Técnico da Propriedade

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#171]
## Descrição da Issue

Criação do endpoint de atualização (PATCH/PUT) de propriedade referente a remoção do técnico

## Tasks:
- [x] Novo endpoint de atualização de propriedade

## Critérios de Aceitação:
- [x] Passar nos testes de integração contínua.
- [x] Revisado pelo time de back-end
