### ISSUE TITLE
US14/US15 - Alterar cultura de um plantio

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#172]
## Descrição da Issue

Criação do endpoint de atualização (PATCH/PUT) de plantio referente a cultura

## Tasks:
- [x] Novo endpoint de atualização de plantio

## Critérios de Aceitação:
- [x] Passar nos testes de integração contínua.
- [x] Revisado pelo time de back-end
