### ISSUE TITLE
Tela de propriedades sem técnico 

### ISSUE THREAD

**Issue by PauloAbiAcl** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#174]
## Descrição da Issue
Criar a tela de propriedades sem técnico no protótipo e realizar a implementação para o projeto.

## Tasks:
- [x] Criação da interface no Protótipo do projeto
- [x] Implementação da tela

## Critérios de Aceitação:
- [x] Estar de acordo com a identidade visual do projeto
- [x] Seguir os padrões de código definidos pelo grupo
