### ISSUE TITLE
Histórico de Plantações

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#176]
## Descrição da Issue
Desenvolver interface que mostre o histórico de plantações de uma determinada propriedade.

## Tasks:
- [x] Desenvolver interface
- [x] Integrar com o servidor

## Critérios de Aceitação:
- [x] Revisão dos membros
- [x] Seguir o protótipo de Alta Fidelidade
