### ISSUE TITLE
Visualização de Culturas

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#180]
## Descrição da Issue

Criação do endpoint de  visualização (GET) de culturas

## Tasks:
- [x] Novo endpoint de visualização de propriedade

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
