### ISSUE TITLE
Visualização de Propriedades sem técnico

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#181]
## Descrição da Issue

Criação do endpoint de  visualização (GET) de propriedades sem técnico

## Tasks:
- [x] Novo endpoint de visualização de propriedade

## Critérios de Aceitação:
- [x] Revisado pelo time de back-end
- [x] Passar nos testes de integração contínua.
