### ISSUE TITLE
Endpoint do histórico de talhão

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#182]
## Descrição da Issue

Necessidade de fazer um endpoint para coletar o histórico de um determinado talhão.

## Tasks:
- [x] Criar endpoint de histórico do talhão
- [x] Fazer testes necessários

## Critérios de Aceitação:
- [x] Passando nos testes de integração
- [x] Aprovado pelo time do backend
