### ISSUE TITLE
Integrar pendências ao frontend

### ISSUE THREAD

**Issue by brenno-silva** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#184]
## Descrição da Issue
Realizar as requisições das pendências

## Tasks:
- [x] Requisição de listagem de pendências
- [x] Requisição de envio de avaliação de agrotóxico

## Critérios de Aceitação:
- [x]  Listar e enviar informações ao backend
