### ISSUE TITLE
Tela Detalhes de Plantação

### ISSUE THREAD

**Issue by vital14** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#190]
## Descrição da Issue
Criação da tela de detalhes de plantação

## Tasks:
- [x] Criação da tela
- [x] Comunicação com o backend

## Critérios de Aceitação:
 - [x] Trazer as informações do plantio de acordo com cada plantio
