### ISSUE TITLE
Apresentação ponto de controle 4 e correções em documentos

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#191]
## Descrição da Issue

- Realização da apresentação e gravação dos 3 vídeos para o quarto ponto de controle e possíveis pequenas correções nos docs

## Tasks:
- [x] Gravação dos vídeos sobre o quarto ponto de controle
- [x] Documentação da entrega no repositório
- [x] Modificação do README
- [x] Possíveis correções nos versionamentos
