### ISSUE TITLE
Criação de Mapa Mental e do Documento Principal 

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#2]
## Descrição da Issue
Adição dos mapas mentais individuais após brainstorm e criação do documento principal contento explicação, fotos e demais artefatos de pré-elicitação. Cada um dos integrantes adicionar a foto do mapa mental nos comentários.

## Tasks:
- [x] Criação dos mapas mentais individuais
- [x] Escolha do mapa mental principal
- [ ] (Opcional) Utilização do Miro
- [x] Documento de pré-elicitação Mapa Mental

**Comment by Joao-Moura** [comment]
![Mind Map](https://user-images.githubusercontent.com/46077033/151263625-b8dd274d-a25e-4a0c-8263-a521b527e16c.jpg)

**Comment by CarlosFiuza** [comment]
![mapa_mental](https://user-images.githubusercontent.com/71738659/151265488-cbe2b145-4295-489b-b6bb-d72677a078a1.png)

**Comment by brenno-silva** [comment]
![MapaMental](https://user-images.githubusercontent.com/54643530/151266427-c78fdc27-e62e-4ebb-b032-d9422f8fd082.png)

**Comment by oEduardoAfonso** [comment]
![Mapa mental](https://user-images.githubusercontent.com/54921791/151275432-2774510b-9f4b-4baf-9778-2e63c5e4816e.jpg)

**Comment by RcleydsonR** [comment]
![image](https://user-images.githubusercontent.com/74625814/151275262-14783bea-8456-48e2-be48-cc96391cbb9b.png)

**Comment by thiagohdaqw** [comment]
# SVG

![mapa](https://user-images.githubusercontent.com/54081877/151790802-1d164317-b6fd-4030-ac3b-6a13df01ef7b.svg)


# PNG
![image](https://user-images.githubusercontent.com/54081877/151790727-0418afb7-46a8-4665-8db9-454e6fff3fe5.png)

**Comment by VitorLamego** [comment]
![Arquitetura e Desenho  - Frame 1](https://user-images.githubusercontent.com/54643464/151435989-18f0d6f5-b611-46e4-a766-67e4fcbefe8d.jpg)

**Comment by Denniel-sudo** [comment]
![Aplicativo de Rastreabilidade Agrícola](https://user-images.githubusercontent.com/54074370/151444452-4a122018-0dba-4214-afd7-87dbda59b558.png)

**Comment by vital14** [comment]
![20220127_212413.jpg](https://user-images.githubusercontent.com/54643459/151465491-f47f3593-f61f-4d81-87c2-b03d1e2abee9.jpg)

**Comment by PauloAbiAcl** [comment]
![Mind Map](https://user-images.githubusercontent.com/78428733/151476340-974efcf8-8d04-4672-a0ad-a290759a38bc.jpg)

**Comment by CarlosFiuza** [comment]
Artefato mapa mental presente na wiki
