### ISSUE TITLE
Criação do documento de Prorização First Thing First

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#27]
## Descrição da Issue

- Realizar a priorização pelo first thing first e criar o documento respectivo

## Tasks:

- [x] Adição do documento com introdução sobre a priorização
- [x] Sintetização dos requisitos do projeto
- [x] Criação da tabela de priorização

**Comment by Joao-Moura** [comment]
Concluída com sucesso
