### ISSUE TITLE
Criação do documento de Modelagem BPMN

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#3]
## Descrição da Issue
Adição do documento de modelagem BPMN

## Tasks:
- [x] Explicação sobre o artefato de modelagem BPMN
- [x] Modelagem utilizada pela equipe
- [x] Fluxogramas para as diversas etapas do desenvolvimento de software
- [x] Referências
