### ISSUE TITLE
Criação do documento de design sprint

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#30]
## Descrição da Issue

Esse documento visa confeccionar a representação dessa sprint design inicial, foi definido o seguinte modelo:

### Unpack
* Brainstorming
* Mapa Mental
* 5w2h

### Sketch
* Rich Picture
* Introspecção
* Entrevista
* Personas
* Storyboard

### Decide
* Moscow
* First things First

### Prototype:
* Protótipo de média fidelidade

## Tasks:
- [x] Criar documento com estrutura padronizada
- [x] Referenciar os artefatos já existentes
- [x] Explicar mudanças abordadas nessa design sprint inicial 

## Critérios de Aceitação:
- [x] Documento estar padronizado
- [x] Documento explicar sprint inicial

**Comment by RcleydsonR** [comment]
![image](https://user-images.githubusercontent.com/74625814/152162700-6996e490-3c4f-4c49-b794-b541efa6b2a2.png)
![image](https://user-images.githubusercontent.com/74625814/152163243-7389dc9b-c02e-4aee-9849-ae7ce4f4dba8.png)
Imagens para ata do dia 31/01

**Comment by RcleydsonR** [comment]
Done .
