### ISSUE TITLE
Criação do Protótipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#31]
## Descrição da Issue
Documentar os protótipos desenvolvidos pelo grupo responsável pela realização do protótipo para que o grupo tenha acesso.

## Tasks:
- [x] Cada membro desenvolver um protótipo de baixa fidelidade
- [x] Descrever quais são as conclusões para a realização do protótipo de média fidelidade

## Critérios de Aceitação:
- [x] Aceitação pelos membros presentes na task

**Comment by VitorLamego** [comment]
![Uploading Frame 3 (2).jpg…]()

**Comment by VitorLamego** [comment]
![Frame 3 (2)](https://user-images.githubusercontent.com/54643464/152067146-b49f654b-d98f-439b-ab5d-bce7f9c1f465.jpg)

**Comment by brenno-silva** [comment]
![Telas1](https://user-images.githubusercontent.com/54643530/152081334-dc2c58b7-1d1d-4614-8ca9-6ed435dd983c.jpg)
![Telas2](https://user-images.githubusercontent.com/54643530/152081344-9b828502-0b7e-4958-a099-fbf9400a78f8.jpg)
![Telas3](https://user-images.githubusercontent.com/54643530/152081054-c3b1f60d-721b-4b8e-bf69-a857c6195b8b.jpg)
![Telas4](https://user-images.githubusercontent.com/54643530/152081058-3bd19bd3-5a68-4ab2-be46-06aa7382cc46.jpg)

**Comment by oEduardoAfonso** [comment]
![image](https://user-images.githubusercontent.com/54921791/152241659-2369dc7b-8fea-415d-90b3-e414a8817233.png)

**Comment by CarlosFiuza** [comment]
![splashScreen](https://user-images.githubusercontent.com/71738659/152243716-043bd3c8-4439-4713-8a14-d43228b8a312.jpg)

![photo_2022-02-02_18-50-35](https://user-images.githubusercontent.com/71738659/152243822-b24b3a82-d63c-441b-b594-eefd9e2e766d.jpg)

![photo_2022-02-02_18-50-38](https://user-images.githubusercontent.com/71738659/152243849-01f1c08e-eb50-4c7b-97ab-1573f5bf842a.jpg)

![photo_2022-02-02_18-50-40](https://user-images.githubusercontent.com/71738659/152243992-5fc72259-0320-4abc-9b63-f069aa288980.jpg)


![photo_2022-02-02_18-50-43](https://user-images.githubusercontent.com/71738659/152244109-50352319-3464-4905-8782-bee502bbe846.jpg)



![photo_2022-02-02_18-50-42](https://user-images.githubusercontent.com/71738659/152244126-9c3d241c-316e-486a-9af1-572f87730944.jpg)

**Comment by Joao-Moura** [comment]
Concluído
