### ISSUE TITLE
Criação do Protótipo de Média Fidelidade

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#32]
## Descrição da Issue
A partir do protótipo de baixa fidelidade, desenvolver um protótipo de média fidelidade para o projeto.

## Tasks:
- [x] Desenvolvimento de um Protótipo de Média Fidelidade em conjunto
- [x] Criação da identidade visual
- [x] Criação da logo (se possível)

## Critérios de Aceitação:
- [x] Aceitação por todos os membros participantes do projeto.

**Comment by Joao-Moura** [comment]
Concluído
