### ISSUE TITLE
Criação do documento do MoSCoW

### ISSUE THREAD

**Issue by vital14** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#35]
## Descrição da Issue
Criação do documento de priorização MoSCoW 

## Tasks:
- [x] Criação do documento
- [x] Adição da tabela de priorização
- [x] Avaliar cada requisito de acordo com sua prioridade
- [x] Chegar as conclusões

## Critérios de Aceitação:
- [x] Aprovação dos participantes em relação ao documento

**Comment by RcleydsonR** [comment]
Done .
