### ISSUE TITLE
Apresentação ponto de controle 1 e correções em documentos

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#39]
## Descrição da Issue

- Realização da apresentação e gravação dos 3 vídeos para o primeiro ponto de controle e possíveis pequenas correções nos docs

## Tasks:

- [x] Gravação dos vídeos sobre o primeiro ponto de controle
- [x] Documentação da entrega no repositório
- [x] Adição do index.md no mkdocs
- [x] Possível correções de docs

**Comment by Joao-Moura** [comment]
Completo
