### ISSUE TITLE
 Criação do documento TAP (Termo de Abertura de Projeto)

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#4]
## Descrição da Issue
Adição do documento do Termo de Abertura do Projeto (TAP)

## Tasks:
- [x] Criação do documento de Termo de Abertura de Projeto
- [x] Adição do documento de gerência de riscos
- [x] Adição do documento de custos

**Comment by Joao-Moura** [comment]
Concluído
