### ISSUE TITLE
Criação do MER (Modelo entidade relacionamento)

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#46]
## Tasks:
- [x] Documentar as entidades
- [x] Documentar o relacionamento entre as entidades

## Critérios de Aceitação:
- [x] Documento deve estar padronizado e ser revisado

**Comment by Joao-Moura** [comment]
Finalizada
