### ISSUE TITLE
Criação do Diagrama de Pacotes

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#47]
## Tasks:

- [x] Texto explicativo sobre a modelagem
- [x] Diagrama de pacotes do frontend
- [x] Diagrama de pacotes do backend

**Comment by Joao-Moura** [comment]
Diagrama de Pacotes backend (Django)
![Diagrama em branco](https://user-images.githubusercontent.com/46077033/153094599-70d0b8d8-9f93-4e91-bada-dcad151924ba.png)

**Comment by VitorLamego** [comment]
![Blank diagram](https://user-images.githubusercontent.com/54643464/153310146-2ee192bb-b232-486f-9d36-542ad49fd382.png)

**Comment by Joao-Moura** [comment]
Completo
