### ISSUE TITLE
Criação da Especificação Suplementar

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#48]
## Descrição da Issue

Adição do documento contendo a especificação suplementar utilizando algum modelo de qualidade. Opcional utilizar o modelo FURPS+

## Tasks:

- [x] Introdução sobre a modelagem escolhida
- [x] Modelagem dos requisitos na especificação suplementar

## Critérios de Aceitação:

- [x] Utilização de pelo menos um modelo de qualidade

**Comment by Joao-Moura** [comment]
Feito
