### ISSUE TITLE
Criação do Diagrama de Atividades

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#58]
## Descrição da Issue

Criar e documentar o diagrama de atividades referente ao projeto.

## Tasks:

- [x] Criar diagrama de atividades do produtor
- [x] Criar diagrama de atividades do técnico

## Critérios de Aceitação:

- [x] Revisado por pares

**Comment by Joao-Moura** [comment]
Revisado e aprovado
