### ISSUE TITLE
Criação do diagrama de comunicação

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#61]
## Descrição da Issue
Criar o diagrama de comunicação no escopo do projeto e adicionar documento explicativo na wiki

## Tasks: 
- [x] Criação dos diagramas
- [x] Criação do documento
- [x] Adição de descrição explicativa sobre o mesmo

## Critérios de Aceitação:
 - [x] Revisão em pares
 - [x] Ao menos 2 diagramas

**Comment by Joao-Moura** [comment]
Finalizado
