### ISSUE TITLE
Criação do diagrama com o NFR Framework

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#62]
## Descrição da Issue

- Criação e documentação dos diagramas advindo da modelagem ágil NFR Framework

## Tasks:

- [x] Introdução sobre o documento
- [x] Adição dos diagramas sem propagação
- [x] Adição dos diagramas com propagação

## Critérios de Aceitação:

- [x] Utilizar os requisitos não funcionais propostos na especificação suplementar

**Comment by Joao-Moura** [comment]
Completo
