### ISSUE TITLE
Criação do Diagrama de Sequências

### ISSUE THREAD

**Issue by vital14** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#63]
## Descrição da Issue
Criar o diagrama de sequências no escopo do projeto e adicionar documento explicativo na wiki

## Tasks: 
- [x] Criação do diagrama
- [x] Criação do documento
- [x] Adição na wiki

## Critérios de Aceitação:
 - [x] Estar na Wiki
