### ISSUE TITLE
 Apresentação ponto de controle 2 e correções em documentos

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#73]
## Descrição da Issue

- Realização da apresentação e gravação dos 2 vídeos para o segundo ponto de controle e possíveis pequenas correções nos docs

## Tasks:
- [x] Gravação dos vídeos sobre o segundo ponto de controle
- [x] Documentação da entrega no repositório
- [x] Modificação do README
- [x] Correções nas Bibliografias para Referências
- [x] Possíveis correções nos versionamentos
- [x] Adição do tópico Reunião ou algo do tipo nos docs
- [x] Alteração da política de branchs
