### ISSUE TITLE
Customização wiki

### ISSUE THREAD

**Issue by CarlosFiuza** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#81]
## Descrição da Issue
Customização da wiki com css

## Tasks:
- [x] Criar landing page para home da wiki
- [x] Aplicar estilos nos documentos

## Critérios de Aceitação:
- [x] Todos do grupo aceitarem
