### ISSUE TITLE
Documentar estudo sobre GOF's criacionais

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#86]
## Descrição da Issue

Issue relacionada a criação do documento de estudo sobre os GOF's criacionais, os escolhidos foram o Factory Method, Abstract Factory, Builder e Prototype.

## Tasks:
- [x] Documentar Factory Method
- [x] Documentar Abstract Factory
- [x] Documentar Builder
- [x] Documentar Prototype

## Critérios de Aceitação:
- [x] Documento revisado por pares e documentado na wiki

**Comment by Joao-Moura** [comment]
Completo
