### ISSUE TITLE
Dojo Backend utilizando Django e django-rest

### ISSUE THREAD

**Issue by Joao-Moura** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#88]
## Descrição da Issue

- Dojo para aprendizagem sobre o backend utilizando os frameworks Django e django-rest
- Será realizado as 22h do dia 24/02 pelo discord da equipe
- Deverá ser gravado e criado um arquivo para documentação do mesmo

## Tasks:

- [x] Realização do dojo
- [x] Gravação do vídeo
- [x] Criação do documento

## Critérios de Aceitação:

- [x] Possuir a gravação do dojo

**Comment by Joao-Moura** [comment]
https://youtu.be/hatJ4TQ58BY
